version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=password
  redis:
    image: 'redis:latest'
  nginx:
    depends_on:
      - api
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - ./server:/usr/src/app
    environment:
      - DEBUG=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # - REDIS_PASSWORD=password
      - DB_USERNAME=postgres
      - DB_HOST=postgres      
      - DB_NAME=postgres
      - DB_PASSWORD=password
      - DB_PORT=5432
  frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
  worker:
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - ./worker:/usr/src/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379